In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df_reference_data = pd.read_csv('888 LETSFLO ASSETS.csv')

In [3]:
df_888_data = pd.read_excel('888 Data.xlsx')

In [4]:
#Clean Barcode for merge preparation, remove ="
#df['column_name'] = df['column_name'].str.replace(r'[abc]', '', regex=True)

df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace(r'="','',regex=True)

In [5]:
#Remove ending in "
df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace('"','',regex=True)

In [6]:
#Remove beginning with 00
df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace('^00','',regex=True)

In [7]:
#Remove 'Home-' from Lighting Type
df_reference_data['TYPE'] = df_reference_data['TYPE'].str.replace('Home-','',regex=True)
df_reference_data.head()

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,RESERVED WBS,LOCATION,ORIGINAL ACQUISITION VALUE,HISTORY,HOME WAREHOUSE,CONTAINER,LAST SEEN IN CONTAINER,BARCODE IMAGES,ASSET USAGE,SIDEMARK ROOM
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,E-12016.16LIC.15.13,LIC,NaN,History,LIC,W01-13-01-BB,"Fri, Apr 4, 2025 1:35 PM",6316601,"E-12016.16LIC.15.13 - Fri, April 4, 2025 - Fri...",STUART WOODS / FOR RL3492BRN-WP / RL235-002
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-06-BB,"Fri, Apr 4, 2025 1:47 PM",7002553,NaN,SP24 CHANGEOVER / 888 STOCK / RETURN FROM 888
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",7003417,NaN,888 STOCK
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",6310188,NaN,MD311 / FA19 CHANGEOVER / MD311
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-15-02-AA,"Thu, Apr 3, 2025 2:51 PM",6315105,NaN,RL5322PN-CA / 888 STOCK

In [8]:
df_reference_data

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,RESERVED WBS,LOCATION,ORIGINAL ACQUISITION VALUE,HISTORY,HOME WAREHOUSE,CONTAINER,LAST SEEN IN CONTAINER,BARCODE IMAGES,ASSET USAGE,SIDEMARK ROOM
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,E-12016.16LIC.15.13,LIC,NaN,History,LIC,W01-13-01-BB,"Fri, Apr 4, 2025 1:35 PM",6316601,"E-12016.16LIC.15.13 - Fri, April 4, 2025 - Fri...",STUART WOODS / FOR RL3492BRN-WP / RL235-002
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-06-BB,"Fri, Apr 4, 2025 1:47 PM",7002553,NaN,SP24 CHANGEOVER / 888 STOCK / RETURN FROM 888
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",7003417,NaN,888 STOCK
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",6310188,NaN,MD311 / FA19 CHANGEOVER / MD311
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-15-02-AA,"Thu, Apr 3, 2025 2:51 PM",6315105,NaN,RL5322PN-CA / 888 STOCK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,6316107,Available,ELLIS BEDSIDE LAMP PN (SHADE) / RL3965PN-Q-P /...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LAMP BASE IS ASSET 006316109,POLISHED NICKEL & QUARTZ,14 x 11 x 10.5,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,"Fri, Jul 22, 2022 4:12 PM",6316107,NaN,888 STOCK / RL3965PN-Q-P
584,6309537,Available,RL ''67 BOOM ARM WALL LAMP IN NB/14029BN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SCRATCHES,NaN,30 x 5 x 22,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,"Wed, Jul 6, 2022 11:14 AM",6309537,NaN,ST.JEAN/ FA19 CHANGEOVER
585,6306761,Available,BARRETT LARGE KNURLED CHAND HARDWARE &SHADES/R...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,006306761 IS THE SECOND PC TO THIS LAMP,NaN,7 x 7 x 4.25,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-BB,NaN,6306761,NaN,888 STOCK
586,6306759,Available,UPTON LARGE LANTERN IN BRONZE/RL5156BZ,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,clear glass has sticky subtance on bottom,NaN,14 x 14 x 29.5,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,NaN,6306759,NaN,888 STOCK
587,6316616,Available,CANNES PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-363-001,NaN,26 x 26 x 28,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-BB,NaN,6316616,NaN,"PO#RMA 7-1522/TRACKING#74060470306773, PO Numb..."

In [9]:
df_reference_data.columns
#Index(['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       #'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       #'RETAIL YEAR'],
   #   dtype='object')

Index(['BARCODE', 'AVAILABILITY', 'DESCRIPTION', 'DEPARTMENT', 'TYPE',
       'IMAGES', 'CONDITION', 'COLOR', 'DIMENSIONS', 'TAGS',
       'CONDITION CHECKS', 'RESERVED WBS', 'LOCATION',
       'ORIGINAL ACQUISITION VALUE', 'HISTORY', 'HOME WAREHOUSE', 'CONTAINER',
       'LAST SEEN IN CONTAINER', 'BARCODE IMAGES', 'ASSET USAGE',
       'SIDEMARK ROOM'],
      dtype='object')

In [10]:
df_reference_data.columns

Index(['BARCODE', 'AVAILABILITY', 'DESCRIPTION', 'DEPARTMENT', 'TYPE',
       'IMAGES', 'CONDITION', 'COLOR', 'DIMENSIONS', 'TAGS',
       'CONDITION CHECKS', 'RESERVED WBS', 'LOCATION',
       'ORIGINAL ACQUISITION VALUE', 'HISTORY', 'HOME WAREHOUSE', 'CONTAINER',
       'LAST SEEN IN CONTAINER', 'BARCODE IMAGES', 'ASSET USAGE',
       'SIDEMARK ROOM'],
      dtype='object')

In [11]:
#remove null column
df_888_data.drop(df_888_data.columns[df_888_data.columns.str.contains('Unnamed', case=False)], axis=1, inplace=True)

In [12]:
#df['column_name'] = df['column_name'].astype(str)
df_888_data['Receiving Report #'] = df_888_data['Receiving Report #'].astype(str)

In [13]:
#Remove .0 on values in Barcode
df_888_data['Receiving Report #'] = df_888_data['Receiving Report #'].str.replace('.0','',regex=False)

In [14]:
#df = df.rename(columns={'col1': 'new_col1', 'col2': 'new_col2'})
df_888_data = df_888_data.rename(columns={'Receiving Report #': 'BARCODE'})

In [15]:
df_888_data = df_888_data[df_888_data['BARCODE'] != 'nan']

In [16]:
df_888_data

,BARCODE,Item #,Item Type,Category,PP Deck (Y/N),Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,NaN,(LAMP SHADE)-RL3080PN-WP,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.000,Y,NaN
1,6311507,NaN,(LAMP SHADE)-RL61004SH,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
2,6314391,NaN,"16.75"" OVAL LINEN SHADE",Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
3,6311505,NaN,17x18x13.5L (LAMP SHADE),Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
4,7001179,NaN,ADRIANNA MEDIUM CHANGELIER,Lighting,NaN,NaN,NaN,26793299,NaN,NaN,0,9969.0,1879.580,Y,2011.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,7000382,NaN,WOVEN OTTOMAN,Furniture,NaN,NaN,Display,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
578,7003186,NaN,WRITERS CHAIR,Furniture,NaN,polo,Display,46036539,NaN,NaN,Sellable,10485.0,2265.000,NaN,2024.0
579,7001907,NaN,XAVIER SMALL PENDANT,Lighting,NaN,NaN,Display,42522615,NaN,NaN,0,1279.0,249.175,Y,2016.0
580,7002883,NaN,WRITER'S OTTOMAN,Furniture,NaN,polo,Display,45261401,NaN,NaN,Sellable,3099.0,872.250,Y,2020.0
581,7001179,NaN,NaN,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [17]:
## Merge with an indicator column
#diff = pd.merge(df1, df2, on=['id', 'value'], how='outer', indicator=True)
# Filter rows where the indicator is not 'both'
#differences = diff[diff['_merge'] != 'both']
#print(differences)
diff_df = pd.merge(df_reference_data, df_888_data, on=['BARCODE'], how='outer', indicator=True)
dif = diff_df[diff_df['_merge'] !='both']
print(dif)

     BARCODE AVAILABILITY                         DESCRIPTION  \
2    6295203    Available  EMPIRE PEDESTAL TABLE - TABLE BASE
15   6303412          NaN                                 NaN
18   6304730          NaN                                 NaN
41   6309527          NaN                                 NaN
59   6310370    Available   NORDY FRITTER ROUND PERCALE-SHADE
..       ...          ...                                 ...
636  7003548    Available                     CUSHING ETAGERE
637  7003549    Available            ANTIQUE ROUND TABLE BASE
638  7003550    Available             ANTIQUE ROUND TABLE TOP
639  7003563    Available               SILK SHADE FOR RL3650
640  7003564    Available                   ROUND PAPER SHADE

           DEPARTMENT      TYPE  \
2    Home 888 Madison     TABLE
15                NaN       NaN
18                NaN       NaN
41                NaN       NaN
59   Home 888 Madison  LIGHTING
..                ...       ...
636  Home 888 Madison   DRESSER
637  Home 888 Madison     TABLE
638  Home 888 Madison     TABLE
639  Home 888 Madison  LIGHTING
640  Home 888 Madison  LIGHTING

                                                IMAGES  \
2    https://flo-rlassets.s3.eu-west-1.amazonaws.co...
15                                                 NaN
18                                                 NaN
41                                                 NaN
59   https://flo-rlassets.s3.eu-west-1.amazonaws.co...
..                                                 ...
636  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
637  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
638  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
639  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
640  https://flo-rlassets.s3.eu-west-1.amazonaws.co...

                                             CONDITION  COLOR  \
2    MINOR SCRATCHES AND DENTS  GOES WITH 006313179...  BLACK
15                                                 NaN    NaN
18                                                 NaN    NaN
41                                                 NaN    NaN
59                                         MINOR MARKS  WHITE
..                                                 ...    ...
636                                                NaN    NaN
637  TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...    NaN
638  TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...    NaN
639                                       MINOR MARKS.  WHITE
640  TOP AND BOTTOM EDGES ARE SLIGHTLY WORN AND DEN...  WHITE

                  DIMENSIONS TAGS  ... Condition       SKU  \
2        28 x 28 x 26 Inches  NaN  ...       NaN       NaN
15                       NaN  NaN  ...       NaN  40359416
18                       NaN  NaN  ...   Display       NaN
41                       NaN  NaN  ...   Display       NaN
59        11 x 13 x 9 Inches  NaN  ...       NaN       NaN
..                       ...  ...  ...       ...       ...
636      50 x 14 x 93 Inches  NaN  ...       NaN       NaN
637    72 x 72 x 30.5 Inches  NaN  ...       NaN       NaN
638    72 x 72 x 30.5 Inches  NaN  ...       NaN       NaN
639      26 x 26 x 18 Inches  NaN  ...       NaN       NaN
640  22.5 x 22.5 x 14 Inches  NaN  ...       NaN       NaN

    DONATION FY26 (Y/N)  Notes Availability Retail($) Cost($) Dest (Y/N)  \
2                   NaN    NaN          NaN       NaN     NaN        NaN
15                  NaN    NaN            0    3000.0   730.0          Y
18                  NaN    NaN            0       0.0     0.0          Y
41                  NaN    NaN            0       0.0     0.0        NaN
59                  NaN    NaN          NaN       NaN     NaN        NaN
..                  ...    ...          ...       ...     ...        ...
636                 NaN    NaN          NaN       NaN     NaN        NaN
637                 NaN    NaN          NaN       NaN     NaN        NaN
638                 NaN    NaN          NaN       NaN     NaN        NaN
639                 NaN    NaN          NaN       NaN     NaN        NaN
640                 NaN    NaN          NaN       NaN     NaN        NaN

     RETAIL YEAR      _merge
2            NaN   left_only
15        2018.0  right_only
18           NaN  right_only
41           NaN  right_only
59           NaN   left_only
..           ...         ...
636          NaN   left_only
637          NaN   left_only
638          NaN   left_only
639          NaN   left_only
640          NaN   left_only

[111 rows x 36 columns]

In [18]:
dif

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR,_merge
2,6295203,Available,EMPIRE PEDESTAL TABLE - TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES AND DENTS GOES WITH 006313179...,BLACK,28 x 28 x 26 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15,6303412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,40359416,NaN,NaN,0,3000.0,730.0,Y,2018.0,right_only
18,6304730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Display,NaN,NaN,NaN,0,0.0,0.0,Y,NaN,right_only
41,6309527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Display,NaN,NaN,NaN,0,0.0,0.0,NaN,NaN,right_only
59,6310370,Available,NORDY FRITTER ROUND PERCALE-SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS,WHITE,11 x 13 x 9 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,7003548,Available,CUSHING ETAGERE,Home 888 Madison,DRESSER,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,NaN,NaN,50 x 14 x 93 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
637,7003549,Available,ANTIQUE ROUND TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
638,7003550,Available,ANTIQUE ROUND TABLE TOP,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
639,7003563,Available,SILK SHADE FOR RL3650,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS.,WHITE,26 x 26 x 18 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
640,7003564,Available,ROUND PAPER SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP AND BOTTOM EDGES ARE SLIGHTLY WORN AND DEN...,WHITE,22.5 x 22.5 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [19]:
#left_only = merged[merged['_merge'] == 'left_only'].drop(columns=['_merge'])

# Add these rows back to the original DataFrame
#f1_updated = pd.concat([df1, left_only], ignore_index=True)

#print(df1_updated)
lets_flo =  dif[dif['_merge'] == 'left_only'].drop(columns=['_merge'])
home_copy = dif[dif['_merge'] == 'right_only'].drop(columns=['_merge'])

In [20]:
lets_flo
#Display 61 rows that are only in the LetsFlo database

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
2,6295203,Available,EMPIRE PEDESTAL TABLE - TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES AND DENTS GOES WITH 006313179...,BLACK,28 x 28 x 26 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,6310370,Available,NORDY FRITTER ROUND PERCALE-SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS,WHITE,11 x 13 x 9 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,7000508,Available,MODERN HOLLYWOOD OTTOMAN,Home 888 Madison,OTTOMAN,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,WOODEN BASE HAS MULTIPLE SCRATCHES AND CHIPS A...,NaN,24 x 24 x 17 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,7002739,Available,EMPIRE PEDESTAL TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH EMPIRE PEDESTAL DINING TABLE TOP: 00...,NaN,40.5 x 40.5 x 26.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,7002860,Available,RAYMOND CLUB CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,FABRIC HAS MULTIPLE LINE MARKS AND MINOR STAIN...,WHITE,35 x 39 x 34 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,7003548,Available,CUSHING ETAGERE,Home 888 Madison,DRESSER,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,NaN,NaN,50 x 14 x 93 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,7003549,Available,ANTIQUE ROUND TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,7003550,Available,ANTIQUE ROUND TABLE TOP,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,7003563,Available,SILK SHADE FOR RL3650,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS.,WHITE,26 x 26 x 18 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,7003564,Available,ROUND PAPER SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP AND BOTTOM EDGES ARE SLIGHTLY WORN AND DEN...,WHITE,22.5 x 22.5 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
home_copy
#Displays 50 rows that only exist in the home copy of the database

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
15,6303412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,40359416,NaN,NaN,0,3000.0,730.000000,Y,2018.0
18,6304730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,Y,NaN
41,6309527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
107,6314131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
209,6318891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43651975,NaN,Missing pieces,0,39000.0,4217.813333,NaN,2020.0
210,6318892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,NaN,NaN,Missing pieces,0,0.0,0.000000,Y,NaN
211,6318893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,42448449,NaN,Missing pieces,0,14486.0,3746.250000,Y,2019.0
212,6318895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43614650,NaN,Missing pieces,0,12595.0,3487.500000,Y,2020.0
213,6318896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,NaN,NaN,Missing pieces,0,0.0,0.000000,Y,NaN
214,6318897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,46036232,NaN,Missing pieces,0,17595.0,4976.785714,Y,2024.0
215,6318898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,46036232,NaN,Missing pieces,0,17595.0,4976.785714,Y,2024.0
220,6318979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,42557371,NaN,NaN,0,4809.0,1079.960000,Y,2012.0
245,7000240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
251,7000512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,42448522,NaN,NaN,Sellable,20985.0,5246.250000,Y,2019.0
270,7000718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,42557371,NaN,NaN,0,4809.0,1079.960000,Y,2012.0
314,7001431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43652072,NaN,NaN,Sellable,5200.0,1712.726000,NaN,2020.0
316,7001663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Polo,Display,75246470,NaN,NaN,Sellable,5545.0,1362.500000,NaN,2024.0
328,7001765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43617748,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
345,7001801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,76860931,NaN,NaN,0,10045.0,2512.500000,Y,2024.0
378,7002169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,45261377,NaN,NaN,Sellable,6603.0,1590.000000,NaN,2020.0
407,7002544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,46036232,NaN,NaN,0,17595.0,4976.785714,Y,2024.0
454,7002631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,Y,NaN
455,7002635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
458,7002639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,75090522,NaN,NaN,Sellable,9013.0,2962.840000,NaN,2024.0
468,7002774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43614478,NaN,NaN,Sellable,7295.0,2250.921667,Y,NaN
486,7002870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,78042579,NaN,NaN,Sellable,0.0,0.000000,Y,2024.0
487,7002875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,45857422,NaN,NaN,0,4695.0,1041.000000,NaN,2024.0
490,7002879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Visual,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
492,7002887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Polo,Display,74544230,NaN,NaN,0,2685.0,657.751000,NaN,2024.0
493,7002888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,41042318,NaN,NaN,0,8710.0,1830.000000,NaN,2018.0
495,7002946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,74544867,NaN,NaN,Sellable,8415.0,1860.000000,NaN,2024.0
497,7002965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43652601,NaN,NaN,0,8860.0,3240.000000,NaN,2020.0
499,7002968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,44891695,NaN,NaN,0,5395.0,1574.250000,NaN,2021.0
515,7002997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,74544867,NaN,NaN,Sellable,8415.0,1860.000000,Y,2024.0
519,7003058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Polo,Display,77225340,NaN,NaN,Sellable,4445.0,1709.820000,Y,2024.0
527,7003071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,74548900,NaN,NaN,Sellable,13050.0,3127.500000,NaN,2024.0
532,7003125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43652338,NaN,NaN,Sellable,11470.0,2833.266667,NaN,2020.0
533,7003126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
534,7003127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Visual,Display,NaN,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
548,7003168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,45000114,NaN,NaN,Sellable,2895.0,911.250000,NaN,2020.0
550,7003170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,NaN,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
552,7003183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,74740457,NaN,NaN,Sellable,5565.0,1586.250000,NaN,2024.0
556,7003188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Polo,Display,43614579,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
563,7003205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43615095,NaN,NaN,Sellable,4095.0,1361.250000,NaN,2020.0
569,7003235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Display,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
571,7003238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,43651546,NaN,NaN,Sellable,9195.0,2550.000000,NaN,2020.0
573,7003240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,74740457,NaN,NaN,Sellable,5565.0,1586.250000,NaN,2024.0
578,7003245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,44079804,NaN,NaN,0,4155.0,945.750000,NaN,2020.0
579,7003246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,45261328,NaN,NaN,0,3463.0,1017.750000,NaN,2020.0
587,7003275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,polo,Display,,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN

In [22]:
#Drop columns if nan values
cleaned_home = home_copy.dropna(axis=1,how='all')
cleaned_home

,BARCODE,Item Type,Category,Ownership,Condition,SKU,Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
15,6303412,HOLLIS FLOOR LAMP IN NATURAL BRASS RL 1130NB,Lighting,NaN,NaN,40359416,NaN,0,3000.0,730.000000,Y,2018.0
18,6304730,BRK ST DIN SID CH/763-28,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,Y,NaN
41,6309527,LAUREL COCKTAIL TABLE / WAXED MAHOGANY / RL395...,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
107,6314131,LARGE TROPHY BOWL,Prop,NaN,NaN,NaN,NaN,0,0.0,0.000000,NaN,NaN
209,6318891,EDWARDIAN BOOKCASE (CABINET 1) / WAXED PINE / ...,Furniture,polo,Display,43651975,Missing pieces,0,39000.0,4217.813333,NaN,2020.0
210,6318892,EDWARDIAN BOOKCASE (CABINET 2) / WAXED PINE / ...,Furniture,polo,Display,NaN,Missing pieces,0,0.0,0.000000,Y,NaN
211,6318893,EDWARDIAN BOOKCASE (CROWN & BASE) / WAXED PINE...,Furniture,polo,Display,42448449,Missing pieces,0,14486.0,3746.250000,Y,2019.0
212,6318895,EDWARDIAN BOOKCASE (CABINET 1) / WAXED PINE / ...,Furniture,polo,Display,43614650,Missing pieces,0,12595.0,3487.500000,Y,2020.0
213,6318896,EDWARDIAN BOOKCASE (CABINET 2) / WAXED PINE / ...,Furniture,polo,Display,NaN,Missing pieces,0,0.0,0.000000,Y,NaN
214,6318897,EDWARDIAN BOOKCASE (CROWN & BASE) / WAXED PINE...,Furniture,polo,Display,46036232,Missing pieces,0,17595.0,4976.785714,Y,2024.0
215,6318898,EDWARDIAN BOOKCASE (SHELVES) / WAXED PINE / RL...,Furniture,polo,Display,46036232,Missing pieces,0,17595.0,4976.785714,Y,2024.0
220,6318979,DANIELA MEDIUM ONE-TIER CHANDELIER,Lighting,NaN,NaN,42557371,NaN,0,4809.0,1079.960000,Y,2012.0
245,7000240,PRYCE BEDROOM CHEST,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
251,7000512,BASALT HALL TABLE BLACK,Furniture,polo,Display,42448522,NaN,Sellable,20985.0,5246.250000,Y,2019.0
270,7000718,DANIELA MEDIUM ONE-TIER CHANDELIER,Lighting,NaN,NaN,42557371,NaN,0,4809.0,1079.960000,Y,2012.0
314,7001431,NOBLE ESTATE BEDSIDE TABLE,Furniture,polo,Display,43652072,NaN,Sellable,5200.0,1712.726000,NaN,2020.0
316,7001663,DALTON SIDE TABLE,Furniture,Polo,Display,75246470,NaN,Sellable,5545.0,1362.500000,NaN,2024.0
328,7001765,CUSHING ETAGERE,Furniture,polo,Display,43617748,NaN,Sellable,0.0,0.000000,NaN,NaN
345,7001801,DUKE BAR CART PIANO BLACK,Furniture,polo,Display,76860931,NaN,0,10045.0,2512.500000,Y,2024.0
378,7002169,DUTCHESS CHAIR,Furniture,polo,Display,45261377,NaN,Sellable,6603.0,1590.000000,NaN,2020.0
407,7002544,EDWARDIAN BOOKCASE (SHELVES 6 AND 12 SHELF HOL...,Furniture,polo,Display,46036232,NaN,0,17595.0,4976.785714,Y,2024.0
454,7002631,DORIS MEDIUM TABLE LAMP SHADE,Lighting,NaN,Display,NaN,NaN,0,0.0,0.000000,Y,NaN
455,7002635,DE MOUTON BENCH,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
458,7002639,NEW BOHEMIAN ARTIST CHAIR,Furniture,polo,Display,75090522,NaN,Sellable,9013.0,2962.840000,NaN,2024.0
468,7002774,CUSHING ETAGERE,Furniture,polo,Display,43614478,NaN,Sellable,7295.0,2250.921667,Y,NaN
486,7002870,JAMAICA WOVEN DINING CHAIR,Furniture,polo,Display,78042579,NaN,Sellable,0.0,0.000000,Y,2024.0
487,7002875,FLORENCE STOREGE OTTOMAN,Furniture,polo,Display,45857422,NaN,0,4695.0,1041.000000,NaN,2024.0
490,7002879,ANTIQUE ROUND TABLE BASE,Furniture,Visual,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
492,7002887,ALWYN ACCENT TABLE,Furniture,Polo,Display,74544230,NaN,0,2685.0,657.751000,NaN,2024.0
493,7002888,MAYFAIR TUFTED CHAIR,Furniture,polo,Display,41042318,NaN,0,8710.0,1830.000000,NaN,2018.0
495,7002946,MAYFAIR TUFTED CHAIR,Furniture,polo,Display,74544867,NaN,Sellable,8415.0,1860.000000,NaN,2024.0
497,7002965,DUKE SQUARE POUF,Furniture,polo,Display,43652601,NaN,0,8860.0,3240.000000,NaN,2020.0
499,7002968,DALEHURST LARGE CONSOLE,Furniture,polo,Display,44891695,NaN,0,5395.0,1574.250000,NaN,2021.0
515,7002997,MAYFAIR TUFTED CHAIR,Furniture,polo,Display,74544867,NaN,Sellable,8415.0,1860.000000,Y,2024.0
519,7003058,BAYNARD CONVO CHAIR,Furniture,Polo,Display,77225340,NaN,Sellable,4445.0,1709.820000,Y,2024.0
527,7003071,MOORE WOOD TABLE TOP ONLY,Furniture,polo,Display,74548900,NaN,Sellable,13050.0,3127.500000,NaN,2024.0
532,7003125,LANGHAM DESK BASE,Furniture,polo,Display,43652338,NaN,Sellable,11470.0,2833.266667,NaN,2020.0
533,7003126,LANGHAM DESK TOP,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
534,7003127,ANTIQUE ROUND TABLE TOP,Furniture,Visual,Display,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
548,7003168,NOBLE ESTATE DINNING CHAIR,Furniture,polo,Display,45000114,NaN,Sellable,2895.0,911.250000,NaN,2020.0
550,7003170,MODERN HOLLYWOOD OTTOMANS,Furniture,polo,Display,NaN,NaN,Sellable,0.0,0.000000,NaN,NaN
552,7003183,RADCLIFFE DINNING ARMCHAIR,Furniture,polo,Display,74740457,NaN,Sellable,5565.0,1586.250000,NaN,2024.0
556,7003188,CONSERVATORY GARDEN HOST CHAIR,Furniture,Polo,Display,43614579,NaN,Sellable,0.0,0.000000,NaN,NaN
563,7003205,NEW BOHEMIAN COCKTAIL TABLE,Furniture,polo,Display,43615095,NaN,Sellable,4095.0,1361.250000,NaN,2020.0
569,7003235,DE MOUTON BED BENCH,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000000,NaN,NaN
571,7003238,BLAKLEY CHEST,Furniture,polo,Display,43651546,NaN,Sellable,9195.0,2550.000000,NaN,2020.0
573,7003240,RADCLIFFE DINNING ARMCHAIR,Furniture,polo,Display,74740457,NaN,Sellable,5565.0,1586.250000,NaN,2024.0
578,7003245,FLORENCE OTTOMAN,Furniture,polo,Display,44079804,NaN,0,4155.0,945.750000,NaN,2020.0
579,7003246,FLORENCE OTTOMAN,Furniture,polo,Display,45261328,NaN,0,3463.0,1017.750000,NaN,2020.0
587,7003275,PARKER DINNING ARMCHAIR,Furniture,polo,Display,,NaN,Sellable,0.0,0.000000,NaN,NaN

In [23]:
#lets_flo.to_csv('onlyflo.csv',index=False)
#home_copy.to_csv('onlyhome.csv',index=False)

In [24]:
df_888_data_cleaned = df_888_data.dropna(axis=1,how='all')
df_888_data_cleaned.head()

,BARCODE,Item Type,Category,Ownership,Condition,SKU,Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,(LAMP SHADE)-RL3080PN-WP,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.00,Y,NaN
1,6311507,(LAMP SHADE)-RL61004SH,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.00,NaN,NaN
2,6314391,"16.75"" OVAL LINEN SHADE",Lighting,NaN,NaN,NaN,NaN,0,0.0,0.00,NaN,NaN
3,6311505,17x18x13.5L (LAMP SHADE),Lighting,NaN,NaN,NaN,NaN,0,0.0,0.00,NaN,NaN
4,7001179,ADRIANNA MEDIUM CHANGELIER,Lighting,NaN,NaN,26793299,NaN,0,9969.0,1879.58,Y,2011.0

In [25]:
df_888_data_cleaned.columns

Index(['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR'],
      dtype='object')

In [26]:
#Remove rows in 888 Data using home_copy as reference
remove_not_flo = pd.merge(df_888_data_cleaned,cleaned_home,on=['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR'], how='left',indicator=True)
#remove_not_flo = remove_not_flo.dropna(axis=1,how='all')
#df1_filtered = merged[merged['_merge'] == 'left_only'].drop(columns=['_merge'])
remove_not_flo_filtered = remove_not_flo[remove_not_flo['_merge'] == 'left_only'].drop(columns=['_merge'])
remove_not_flo_filtered

,BARCODE,Item Type,Category,Ownership,Condition,SKU,Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,(LAMP SHADE)-RL3080PN-WP,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.000,Y,NaN
1,6311507,(LAMP SHADE)-RL61004SH,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
2,6314391,"16.75"" OVAL LINEN SHADE",Lighting,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
3,6311505,17x18x13.5L (LAMP SHADE),Lighting,NaN,NaN,NaN,NaN,0,0.0,0.000,NaN,NaN
4,7001179,ADRIANNA MEDIUM CHANGELIER,Lighting,NaN,NaN,26793299,NaN,0,9969.0,1879.580,Y,2011.0
...,...,...,...,...,...,...,...,...,...,...,...,...
575,7000382,WOVEN OTTOMAN,Furniture,NaN,Display,NaN,NaN,0,0.0,0.000,NaN,NaN
576,7003186,WRITERS CHAIR,Furniture,polo,Display,46036539,NaN,Sellable,10485.0,2265.000,NaN,2024.0
577,7001907,XAVIER SMALL PENDANT,Lighting,NaN,Display,42522615,NaN,0,1279.0,249.175,Y,2016.0
578,7002883,WRITER'S OTTOMAN,Furniture,polo,Display,45261401,NaN,Sellable,3099.0,872.250,Y,2020.0
579,7001179,NaN,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [27]:
lets_flo

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
2,6295203,Available,EMPIRE PEDESTAL TABLE - TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES AND DENTS GOES WITH 006313179...,BLACK,28 x 28 x 26 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,6310370,Available,NORDY FRITTER ROUND PERCALE-SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS,WHITE,11 x 13 x 9 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,7000508,Available,MODERN HOLLYWOOD OTTOMAN,Home 888 Madison,OTTOMAN,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,WOODEN BASE HAS MULTIPLE SCRATCHES AND CHIPS A...,NaN,24 x 24 x 17 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,7002739,Available,EMPIRE PEDESTAL TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH EMPIRE PEDESTAL DINING TABLE TOP: 00...,NaN,40.5 x 40.5 x 26.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,7002860,Available,RAYMOND CLUB CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,FABRIC HAS MULTIPLE LINE MARKS AND MINOR STAIN...,WHITE,35 x 39 x 34 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,7003548,Available,CUSHING ETAGERE,Home 888 Madison,DRESSER,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,NaN,NaN,50 x 14 x 93 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,7003549,Available,ANTIQUE ROUND TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,7003550,Available,ANTIQUE ROUND TABLE TOP,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,7003563,Available,SILK SHADE FOR RL3650,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS.,WHITE,26 x 26 x 18 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,7003564,Available,ROUND PAPER SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP AND BOTTOM EDGES ARE SLIGHTLY WORN AND DEN...,WHITE,22.5 x 22.5 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#Add data from lets_flo df to 888 Data
#Save CSV
lets_flo.columns

Index(['BARCODE', 'AVAILABILITY', 'DESCRIPTION', 'DEPARTMENT', 'TYPE',
       'IMAGES', 'CONDITION', 'COLOR', 'DIMENSIONS', 'TAGS',
       'CONDITION CHECKS', 'RESERVED WBS', 'LOCATION',
       'ORIGINAL ACQUISITION VALUE', 'HISTORY', 'HOME WAREHOUSE', 'CONTAINER',
       'LAST SEEN IN CONTAINER', 'BARCODE IMAGES', 'ASSET USAGE',
       'SIDEMARK ROOM', 'Item #', 'Item Type', 'Category', 'PP Deck (Y/N)',
       'Ownership', 'Condition', 'SKU', 'DONATION FY26 (Y/N)', 'Notes',
       'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)', 'RETAIL YEAR'],
      dtype='object')

In [29]:
lets_flo = lets_flo.drop(columns=['Category','Item Type','Availability'])
lets_flo

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,PP Deck (Y/N),Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
2,6295203,Available,EMPIRE PEDESTAL TABLE - TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES AND DENTS GOES WITH 006313179...,BLACK,28 x 28 x 26 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,6310370,Available,NORDY FRITTER ROUND PERCALE-SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS,WHITE,11 x 13 x 9 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,7000508,Available,MODERN HOLLYWOOD OTTOMAN,Home 888 Madison,OTTOMAN,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,WOODEN BASE HAS MULTIPLE SCRATCHES AND CHIPS A...,NaN,24 x 24 x 17 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,7002739,Available,EMPIRE PEDESTAL TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH EMPIRE PEDESTAL DINING TABLE TOP: 00...,NaN,40.5 x 40.5 x 26.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,7002860,Available,RAYMOND CLUB CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,FABRIC HAS MULTIPLE LINE MARKS AND MINOR STAIN...,WHITE,35 x 39 x 34 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,7003548,Available,CUSHING ETAGERE,Home 888 Madison,DRESSER,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,NaN,NaN,50 x 14 x 93 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,7003549,Available,ANTIQUE ROUND TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,7003550,Available,ANTIQUE ROUND TABLE TOP,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,7003563,Available,SILK SHADE FOR RL3650,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS.,WHITE,26 x 26 x 18 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,7003564,Available,ROUND PAPER SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP AND BOTTOM EDGES ARE SLIGHTLY WORN AND DEN...,WHITE,22.5 x 22.5 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
lets_flo = lets_flo.rename(columns = {'AVAILABILITY': 'Availability', 'DESCRIPTION': 'Item Type', 'TYPE' : 'Category'
                                     })

In [31]:
lets_flo.columns

Index(['BARCODE', 'Availability', 'Item Type', 'DEPARTMENT', 'Category',
       'IMAGES', 'CONDITION', 'COLOR', 'DIMENSIONS', 'TAGS',
       'CONDITION CHECKS', 'RESERVED WBS', 'LOCATION',
       'ORIGINAL ACQUISITION VALUE', 'HISTORY', 'HOME WAREHOUSE', 'CONTAINER',
       'LAST SEEN IN CONTAINER', 'BARCODE IMAGES', 'ASSET USAGE',
       'SIDEMARK ROOM', 'Item #', 'PP Deck (Y/N)', 'Ownership', 'Condition',
       'SKU', 'DONATION FY26 (Y/N)', 'Notes', 'Retail($)', 'Cost($)',
       'Dest (Y/N)', 'RETAIL YEAR'],
      dtype='object')

In [32]:
lets_flo = lets_flo[['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR']]

In [33]:
lets_flo

,BARCODE,Item Type,Category,Ownership,Condition,SKU,Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
2,6295203,EMPIRE PEDESTAL TABLE - TABLE BASE,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
59,6310370,NORDY FRITTER ROUND PERCALE-SHADE,LIGHTING,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
250,7000508,MODERN HOLLYWOOD OTTOMAN,OTTOMAN,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
461,7002739,EMPIRE PEDESTAL TABLE BASE,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
481,7002860,RAYMOND CLUB CHAIR,CHAIR,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
636,7003548,CUSHING ETAGERE,DRESSER,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
637,7003549,ANTIQUE ROUND TABLE BASE,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
638,7003550,ANTIQUE ROUND TABLE TOP,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
639,7003563,SILK SHADE FOR RL3650,LIGHTING,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
640,7003564,ROUND PAPER SHADE,LIGHTING,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN

In [34]:
lets_flo.columns

Index(['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR'],
      dtype='object')

In [35]:
final_df = pd.merge(remove_not_flo_filtered,lets_flo, on=['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR'],how='outer')

In [36]:
final_df

,BARCODE,Item Type,Category,Ownership,Condition,SKU,Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6292854,ROUND SHADE ROOM CH,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.0,Y,NaN
1,6294868,ALLEN FLOOR LAMP IN POLISHED,Lighting,NaN,NaN,NaN,NaN,0,0.0,0.0,Y,NaN
2,6295203,EMPIRE PEDESTAL TABLE - TABLE BASE,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
3,6295898,Mordern Hollywood Ottoman RA11474 - NORRIS/SCHAPE,Furniture,NaN,Display,NaN,NaN,0,0.0,0.0,NaN,NaN
4,6295995,TABLE TOP PERSONAL STORAGE /ALALI,Furniture,NaN,Display,NaN,NaN,0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
586,7003548,CUSHING ETAGERE,DRESSER,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
587,7003549,ANTIQUE ROUND TABLE BASE,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
588,7003550,ANTIQUE ROUND TABLE TOP,TABLE,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
589,7003563,SILK SHADE FOR RL3650,LIGHTING,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN
590,7003564,ROUND PAPER SHADE,LIGHTING,NaN,NaN,NaN,NaN,Available,NaN,NaN,NaN,NaN

In [41]:
unique = final_df['BARCODE'].nunique
print(unique)

<bound method IndexOpsMixin.nunique of 0      6292854
1      6294868
2      6295203
3      6295898
4      6295995
        ...
586    7003548
587    7003549
588    7003550
589    7003563
590    7003564
Name: BARCODE, Length: 591, dtype: object>

In [42]:
df_888_data.columns

Index(['BARCODE', 'Item #', 'Item Type', 'Category', 'PP Deck (Y/N)',
       'Ownership', 'Condition', 'SKU', 'DONATION FY26 (Y/N)', 'Notes',
       'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)', 'RETAIL YEAR'],
      dtype='object')

In [43]:
final_df.columns

Index(['BARCODE', 'Item Type', 'Category', 'Ownership', 'Condition', 'SKU',
       'Notes', 'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)',
       'RETAIL YEAR'],
      dtype='object')

In [47]:
#Item #,DONATION FY26 (Y/N),PP Deck (Y/N) add columns
final_df['Item #']=None
final_df['DONATION FY26 (Y/N)']=None
final_df['PP Deck (Y/N)']=None
final_df = final_df[['BARCODE', 'Item #', 'Item Type', 'Category', 'PP Deck (Y/N)',
       'Ownership', 'Condition', 'SKU', 'DONATION FY26 (Y/N)', 'Notes',
       'Availability', 'Retail($)', 'Cost($)', 'Dest (Y/N)', 'RETAIL YEAR']]

In [48]:
final_df

,BARCODE,Item #,Item Type,Category,PP Deck (Y/N),Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6292854,None,ROUND SHADE ROOM CH,Lighting,None,NaN,NaN,NaN,None,NaN,0,0.0,0.0,Y,NaN
1,6294868,None,ALLEN FLOOR LAMP IN POLISHED,Lighting,None,NaN,NaN,NaN,None,NaN,0,0.0,0.0,Y,NaN
2,6295203,None,EMPIRE PEDESTAL TABLE - TABLE BASE,TABLE,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN
3,6295898,None,Mordern Hollywood Ottoman RA11474 - NORRIS/SCHAPE,Furniture,None,NaN,Display,NaN,None,NaN,0,0.0,0.0,NaN,NaN
4,6295995,None,TABLE TOP PERSONAL STORAGE /ALALI,Furniture,None,NaN,Display,NaN,None,NaN,0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,7003548,None,CUSHING ETAGERE,DRESSER,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN
587,7003549,None,ANTIQUE ROUND TABLE BASE,TABLE,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN
588,7003550,None,ANTIQUE ROUND TABLE TOP,TABLE,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN
589,7003563,None,SILK SHADE FOR RL3650,LIGHTING,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN
590,7003564,None,ROUND PAPER SHADE,LIGHTING,None,NaN,NaN,NaN,None,NaN,Available,NaN,NaN,NaN,NaN

In [ ]:
final_df.to_csv('ou