In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df_reference_data = pd.read_csv('888 LETSFLO ASSETS.csv')

In [3]:
#Clean Barcode for merge preparation, remove ="
#df['column_name'] = df['column_name'].str.replace(r'[abc]', '', regex=True)

df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace(r'="','',regex=True)

In [4]:
#Remove ending in "
df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace('"','',regex=True)

In [5]:
#Remove beginning with 00
df_reference_data['BARCODE'] = df_reference_data['BARCODE'].str.replace('^00','',regex=True)

In [6]:
#Remove 'Home-' from Lighting Type
df_reference_data['TYPE'] = df_reference_data['TYPE'].str.replace('Home-','',regex=True)
df_reference_data.head()

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,RESERVED WBS,LOCATION,ORIGINAL ACQUISITION VALUE,HISTORY,HOME WAREHOUSE,CONTAINER,LAST SEEN IN CONTAINER,BARCODE IMAGES,ASSET USAGE,SIDEMARK ROOM
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,E-12016.16LIC.15.13,LIC,NaN,History,LIC,W01-13-01-BB,"Fri, Apr 4, 2025 1:35 PM",6316601,"E-12016.16LIC.15.13 - Fri, April 4, 2025 - Fri...",STUART WOODS / FOR RL3492BRN-WP / RL235-002
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-06-BB,"Fri, Apr 4, 2025 1:47 PM",7002553,NaN,SP24 CHANGEOVER / 888 STOCK / RETURN FROM 888
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",7003417,NaN,888 STOCK
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",6310188,NaN,MD311 / FA19 CHANGEOVER / MD311
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-15-02-AA,"Thu, Apr 3, 2025 2:51 PM",6315105,NaN,RL5322PN-CA / 888 STOCK

In [7]:
df_reference_data

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,RESERVED WBS,LOCATION,ORIGINAL ACQUISITION VALUE,HISTORY,HOME WAREHOUSE,CONTAINER,LAST SEEN IN CONTAINER,BARCODE IMAGES,ASSET USAGE,SIDEMARK ROOM
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,E-12016.16LIC.15.13,LIC,NaN,History,LIC,W01-13-01-BB,"Fri, Apr 4, 2025 1:35 PM",6316601,"E-12016.16LIC.15.13 - Fri, April 4, 2025 - Fri...",STUART WOODS / FOR RL3492BRN-WP / RL235-002
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-06-BB,"Fri, Apr 4, 2025 1:47 PM",7002553,NaN,SP24 CHANGEOVER / 888 STOCK / RETURN FROM 888
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",7003417,NaN,888 STOCK
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-14-04-AA,"Fri, Apr 4, 2025 10:26 AM",6310188,NaN,MD311 / FA19 CHANGEOVER / MD311
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,LIC,NaN,History,LIC,W01-15-02-AA,"Thu, Apr 3, 2025 2:51 PM",6315105,NaN,RL5322PN-CA / 888 STOCK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,6316107,Available,ELLIS BEDSIDE LAMP PN (SHADE) / RL3965PN-Q-P /...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LAMP BASE IS ASSET 006316109,POLISHED NICKEL & QUARTZ,14 x 11 x 10.5,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,"Fri, Jul 22, 2022 4:12 PM",6316107,NaN,888 STOCK / RL3965PN-Q-P
584,6309537,Available,RL ''67 BOOM ARM WALL LAMP IN NB/14029BN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SCRATCHES,NaN,30 x 5 x 22,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,"Wed, Jul 6, 2022 11:14 AM",6309537,NaN,ST.JEAN/ FA19 CHANGEOVER
585,6306761,Available,BARRETT LARGE KNURLED CHAND HARDWARE &SHADES/R...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,006306761 IS THE SECOND PC TO THIS LAMP,NaN,7 x 7 x 4.25,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-BB,NaN,6306761,NaN,888 STOCK
586,6306759,Available,UPTON LARGE LANTERN IN BRONZE/RL5156BZ,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,clear glass has sticky subtance on bottom,NaN,14 x 14 x 29.5,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-CC,NaN,6306759,NaN,888 STOCK
587,6316616,Available,CANNES PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-363-001,NaN,26 x 26 x 28,NaN,...,NaN,LIC,NaN,History,LIC,W01-13-01-BB,NaN,6316616,NaN,"PO#RMA 7-1522/TRACKING#74060470306773, PO Numb..."

In [8]:
df_888_data = pd.read_csv('888 Data.csv')

In [9]:
#remove null column
df_888_data.drop(df_888_data.columns[df_888_data.columns.str.contains('Unnamed', case=False)], axis=1, inplace=True)

In [10]:
#df['column_name'] = df['column_name'].astype(str)
df_888_data['Receiving Report #'] = df_888_data['Receiving Report #'].astype(str)

In [11]:
#Remove .0 on values in Barcode
df_888_data['Receiving Report #'] = df_888_data['Receiving Report #'].str.replace('.0','',regex=False)

In [12]:
#df = df.rename(columns={'col1': 'new_col1', 'col2': 'new_col2'})
df_888_data = df_888_data.rename(columns={'Receiving Report #': 'BARCODE'})

In [13]:
df_888_data

,BARCODE,Item #,Item Type,Category,PP Deck (Y/N),Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,NaN,(LAMP SHADE)-RL3080PN-WP,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
1,6311507,NaN,(LAMP SHADE)-RL61004SH,Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
2,6314391,NaN,"16.75"" OVAL LINEN SHADE",Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
3,6311505,NaN,17x18x13.5L (LAMP SHADE),Lighting,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
4,7001179,NaN,ADRIANNA MEDIUM CHANGELIER,Lighting,NaN,NaN,NaN,26793299,NaN,NaN,0,"$9,969","$1,880",Y,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Merged dataframes for matching data
matching_df = pd.merge(df_reference_data,df_888_data, on='BARCODE',how='inner')

In [15]:
matching_df.head()

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,Display,NaN,NaN,NaN,0,$-,$-,Y,NaN
2,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
3,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,NaN,42557298,NaN,NaN,0,"$3,689",$869,Y,2018
4,7003276,Available,ANNETTE FLOOR LAMP PN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES ON LAMP PACK IN PARTS INBOX . ...,POLISHED NICKEL,43 x 13 x 7.5 Inches,NaN,...,NaN,Display,42485250,NaN,NaN,0,$879,$282,Y,2019

In [16]:
matching_df

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,Display,NaN,NaN,NaN,0,$-,$-,Y,NaN
2,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
3,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,NaN,42557298,NaN,NaN,0,"$3,689",$869,Y,2018
4,7003276,Available,ANNETTE FLOOR LAMP PN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES ON LAMP PACK IN PARTS INBOX . ...,POLISHED NICKEL,43 x 13 x 7.5 Inches,NaN,...,NaN,Display,42485250,NaN,NaN,0,$879,$282,Y,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,6316107,Available,ELLIS BEDSIDE LAMP PN (SHADE) / RL3965PN-Q-P /...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LAMP BASE IS ASSET 006316109,POLISHED NICKEL & QUARTZ,14 x 11 x 10.5,NaN,...,NaN,NaN,42485490,NaN,NaN,0,"$2,639",$679,Y,2019
526,6309537,Available,RL ''67 BOOM ARM WALL LAMP IN NB/14029BN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SCRATCHES,NaN,30 x 5 x 22,NaN,...,NaN,NaN,42559351,NaN,NaN,0,$769,$188,Y,2010
527,6306761,Available,BARRETT LARGE KNURLED CHAND HARDWARE &SHADES/R...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,006306761 IS THE SECOND PC TO THIS LAMP,NaN,7 x 7 x 4.25,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
528,6306759,Available,UPTON LARGE LANTERN IN BRONZE/RL5156BZ,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,clear glass has sticky subtance on bottom,NaN,14 x 14 x 29.5,NaN,...,NaN,NaN,42559617,NaN,NaN,0,"$2,189",$470,Y,2024
529,6316616,Available,CANNES PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-363-001,NaN,26 x 26 x 28,NaN,...,NaN,NaN,42556860,NaN,NaN,0,"$3,229",$580,Y,2024

In [29]:
#Merge dataframes for unmatching data
different_df = pd.merge(df_reference_data,df_888_data, on='BARCODE',how='left')

In [30]:
different_df

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,Display,NaN,NaN,NaN,0,$-,$-,Y,NaN
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,NaN,42557298,NaN,NaN,0,"$3,689",$869,Y,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,6316107,Available,ELLIS BEDSIDE LAMP PN (SHADE) / RL3965PN-Q-P /...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LAMP BASE IS ASSET 006316109,POLISHED NICKEL & QUARTZ,14 x 11 x 10.5,NaN,...,NaN,NaN,42485490,NaN,NaN,0,"$2,639",$679,Y,2019
587,6309537,Available,RL ''67 BOOM ARM WALL LAMP IN NB/14029BN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SCRATCHES,NaN,30 x 5 x 22,NaN,...,NaN,NaN,42559351,NaN,NaN,0,$769,$188,Y,2010
588,6306761,Available,BARRETT LARGE KNURLED CHAND HARDWARE &SHADES/R...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,006306761 IS THE SECOND PC TO THIS LAMP,NaN,7 x 7 x 4.25,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
589,6306759,Available,UPTON LARGE LANTERN IN BRONZE/RL5156BZ,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,clear glass has sticky subtance on bottom,NaN,14 x 14 x 29.5,NaN,...,NaN,NaN,42559617,NaN,NaN,0,"$2,189",$470,Y,2024
590,6316616,Available,CANNES PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-363-001,NaN,26 x 26 x 28,NaN,...,NaN,NaN,42556860,NaN,NaN,0,"$3,229",$580,Y,2024

In [31]:
different_df_cleaned = different_df.dropna(subset=['DESCRIPTION'])
different_df_cleaned

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6316601,Unavailable,ROUND WHITE PAPER CLOSED TOP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-235-002\rRL 3492BRN WP MINO...,WHITE,18 x 18 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
1,7002553,Available,HIGHCROFT LARGE TABLE LAMP SHADE,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HIGHCROFT LARGE TABLE LAMP: 00700255...,WHITE,18 x 12.5 x 12 Inches,NaN,...,NaN,Display,NaN,NaN,NaN,0,$-,$-,Y,NaN
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6310188,Available,SQUARE CLOSED TOP PERCAL TO RL3966PN/Q-P,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH 006310187,WHITE,16 x 16 x 12 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
4,6315105,Available,DALEY MEDUIM SIX LIGHT CHANDELIER PN / RL5322P...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SOME FINGERPRINTS ON CHANDELIER,POLISHED NICKEL,59 x 7 x 31.5 Inches,NaN,...,NaN,NaN,42557298,NaN,NaN,0,"$3,689",$869,Y,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,6316107,Available,ELLIS BEDSIDE LAMP PN (SHADE) / RL3965PN-Q-P /...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LAMP BASE IS ASSET 006316109,POLISHED NICKEL & QUARTZ,14 x 11 x 10.5,NaN,...,NaN,NaN,42485490,NaN,NaN,0,"$2,639",$679,Y,2019
587,6309537,Available,RL ''67 BOOM ARM WALL LAMP IN NB/14029BN,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,SCRATCHES,NaN,30 x 5 x 22,NaN,...,NaN,NaN,42559351,NaN,NaN,0,$769,$188,Y,2010
588,6306761,Available,BARRETT LARGE KNURLED CHAND HARDWARE &SHADES/R...,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,006306761 IS THE SECOND PC TO THIS LAMP,NaN,7 x 7 x 4.25,NaN,...,NaN,NaN,NaN,NaN,NaN,0,$-,$-,Y,NaN
589,6306759,Available,UPTON LARGE LANTERN IN BRONZE/RL5156BZ,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,clear glass has sticky subtance on bottom,NaN,14 x 14 x 29.5,NaN,...,NaN,NaN,42559617,NaN,NaN,0,"$2,189",$470,Y,2024
590,6316616,Available,CANNES PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODE #61425-363-001,NaN,26 x 26 x 28,NaN,...,NaN,NaN,42556860,NaN,NaN,0,"$3,229",$580,Y,2024

In [32]:
print(different_df_cleaned['BARCODE'].nunique())

588

In [33]:
# Filter duplicate values from 'column_name'
#duplicates = df[df['column_name'].duplicated(keep=False)]
duplicates = different_df_cleaned[different_df_cleaned['BARCODE'].duplicated(keep=False)]
print(duplicates)

     BARCODE AVAILABILITY                        DESCRIPTION  \
303  7001749    Available                   CF1 LOUNGE CHAIR
304  7001749    Available                   CF1 LOUNGE CHAIR
377  6313179    Available  EMPIRE PEDESTAL TABLE TOP/1867-20
378  6313179    Available  EMPIRE PEDESTAL TABLE TOP/1867-20
505  7001179    Available         ADRIANNA MEDIUM CHANGELIER
506  7001179    Available         ADRIANNA MEDIUM CHANGELIER

           DEPARTMENT       TYPE  \
303  Home 888 Madison      CHAIR
304  Home 888 Madison      CHAIR
377  Home 888 Madison  TABLE TOP
378  Home 888 Madison  TABLE TOP
505  Home 888 Madison   LIGHTING
506  Home 888 Madison   LIGHTING

                                                IMAGES  \
303  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
304  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
377  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
378  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
505  https://flo-rlassets.s3.eu-west-1.amazonaws.co...
506  https://flo-rlassets.s3.eu-west-1.amazonaws.co...

                                             CONDITION  COLOR  \
303  LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...    NaN
304  LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...    NaN
377      MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP  BLACK
378      MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP  BLACK
505                 MULTIPLE MARKS VISIBLE THROUGHOUT.    NaN
506                 MULTIPLE MARKS VISIBLE THROUGHOUT.    NaN

              DIMENSIONS TAGS  ... Ownership Condition       SKU  \
303  35 x 34 x 30 Inches  NaN  ...      polo   Display  16642563
304  35 x 34 x 30 Inches  NaN  ...      polo   Display  44881852
377  82 x 82 x 58 Inches  NaN  ...      polo   Display       NaN
378  82 x 82 x 58 Inches  NaN  ...      polo   Display       NaN
505  38 x 38 x 44 Inches  NaN  ...       NaN       NaN  26793299
506  38 x 38 x 44 Inches  NaN  ...       NaN       NaN       NaN

     DONATION FY26 (Y/N) Notes Availability  Retail($)    Cost($)  Dest (Y/N)  \
303                  NaN   NaN     Sellable    $16,500    $4,940          NaN
304                  NaN   NaN     Sellable    $10,610    $2,040           Y
377                  NaN   NaN            0       $-        $-            NaN
378                  NaN   NaN            0       $-        $-            NaN
505                  NaN   NaN            0     $9,969    $1,880            Y
506                  NaN   NaN          NaN         NaN       NaN          Y

    RETAIL YEAR
303        2006
304        2020
377         NaN
378         NaN
505        2011
506         NaN

[6 rows x 35 columns]

In [34]:
duplicates
#Noted that same barcode but different SKUs, Different Retail/Cost

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
303,7001749,Available,CF1 LOUNGE CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...,NaN,35 x 34 x 30 Inches,NaN,...,polo,Display,16642563,NaN,NaN,Sellable,"$16,500","$4,940",NaN,2006
304,7001749,Available,CF1 LOUNGE CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...,NaN,35 x 34 x 30 Inches,NaN,...,polo,Display,44881852,NaN,NaN,Sellable,"$10,610","$2,040",Y,2020
377,6313179,Available,EMPIRE PEDESTAL TABLE TOP/1867-20,Home 888 Madison,TABLE TOP,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP,BLACK,82 x 82 x 58 Inches,NaN,...,polo,Display,NaN,NaN,NaN,0,$-,$-,NaN,NaN
378,6313179,Available,EMPIRE PEDESTAL TABLE TOP/1867-20,Home 888 Madison,TABLE TOP,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP,BLACK,82 x 82 x 58 Inches,NaN,...,polo,Display,NaN,NaN,NaN,0,$-,$-,NaN,NaN
505,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,26793299,NaN,NaN,0,"$9,969","$1,880",Y,2011
506,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [35]:
#Make 888 Data as reference
home_df = pd.merge(df_reference_data,df_888_data, on='BARCODE',how='right')
home_df

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,Available,(LAMP SHADE)-RL3080PN-WP,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND MARKS,WHITE,10 x 10 x 10 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
1,6311507,Available,(LAMP SHADE)-RL61004SH,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARK,WHITE,20 x 20 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
2,6314391,Available,"16.75"" OVAL LINEN SHADE",Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES,WHITE,15 x 9.5 x 10.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
3,6311505,Available,17x18x13.5L (LAMP SHADE),Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS AND LOOSE PLASTIC WRAPPING ON THE ...,WHITE,18 x 18 x 13.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
4,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,26793299,NaN,NaN,0,"$9,969","$1,880",Y,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
home_df = home_df.dropna(subset=['DESCRIPTION'])
home_df

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
0,6311506,Available,(LAMP SHADE)-RL3080PN-WP,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND MARKS,WHITE,10 x 10 x 10 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,Y,NaN
1,6311507,Available,(LAMP SHADE)-RL61004SH,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARK,WHITE,20 x 20 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
2,6314391,Available,"16.75"" OVAL LINEN SHADE",Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES,WHITE,15 x 9.5 x 10.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
3,6311505,Available,17x18x13.5L (LAMP SHADE),Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS AND LOOSE PLASTIC WRAPPING ON THE ...,WHITE,18 x 18 x 13.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
4,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,26793299,NaN,NaN,0,"$9,969","$1,880",Y,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,7000382,Available,WOVEN OTTOMAN,Home 888 Madison,OTTOMAN,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES ALONG WITH BROKEN WICKER AL...,WOODEN,17 x 17 x 20 Inches,NaN,...,NaN,Display,NaN,NaN,NaN,0,$-,$-,NaN,NaN
577,7003186,Available,WRITERS CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,CHIP AND SCRATCHES TO FRONT AND BACK WOOD LEG...,"BEIGE ,WHITE AND BLUE",41 x 41 x 37 Inches,NaN,...,polo,Display,46036539,NaN,NaN,Sellable,"$10,485","$2,265",NaN,2024
578,7001907,Available,XAVIER SMALL PENDANT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND VISIBLE DISCOLORATION T...,NATURAL BRASS,14 x 14 x 23.5 Inches,NaN,...,NaN,Display,42522615,NaN,NaN,0,"$1,279",$249,Y,2016
579,7002883,Available,WRITER'S OTTOMAN,Home 888 Madison,OTTOMAN,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,WRINKLING VISIBLE TO FABRIC ON SIDES AND EDGES...,BEIGE/BLUE STRIPES,32 x 27 x 13 Inches,NaN,...,polo,Display,45261401,NaN,NaN,Sellable,"$3,099",$872,Y,2020
580,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [37]:
print(home_df['BARCODE'].nunique())

527

In [38]:
#Print dupes
dupes = home_df[home_df['BARCODE'].duplicated(keep=False)]
dupes

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
4,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,26793299,NaN,NaN,0,"$9,969","$1,880",Y,2011
205,7001749,Available,CF1 LOUNGE CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...,NaN,35 x 34 x 30 Inches,NaN,...,polo,Display,16642563,NaN,NaN,Sellable,"$16,500","$4,940",NaN,2006
332,6313179,Available,EMPIRE PEDESTAL TABLE TOP/1867-20,Home 888 Madison,TABLE TOP,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP,BLACK,82 x 82 x 58 Inches,NaN,...,polo,Display,NaN,NaN,NaN,0,$-,$-,NaN,NaN
334,6313179,Available,EMPIRE PEDESTAL TABLE TOP/1867-20,Home 888 Madison,TABLE TOP,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR DENTS AND SCRATCHES THROUGHOUT TABLETOP,BLACK,82 x 82 x 58 Inches,NaN,...,polo,Display,NaN,NaN,NaN,0,$-,$-,NaN,NaN
449,7001749,Available,CF1 LOUNGE CHAIR,Home 888 Madison,CHAIR,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,LEATHER HAS MULTIPLE SCRATCHES AND SCUFF MARKS...,NaN,35 x 34 x 30 Inches,NaN,...,polo,Display,44881852,NaN,NaN,Sellable,"$10,610","$2,040",Y,2020
580,7001179,Available,ADRIANNA MEDIUM CHANGELIER,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE MARKS VISIBLE THROUGHOUT.,NaN,38 x 38 x 44 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN

In [44]:
#Make Excel Spreadsheet using from LetsFlo data as reference merge
different_df_cleaned.to_csv('Output/output.csv',index=False)

In [45]:
#Display differences in both 
concat_df = pd.concat([different_df_cleaned,home_df]).drop_duplicates(keep=False)

In [46]:
concat_df

,BARCODE,AVAILABILITY,DESCRIPTION,DEPARTMENT,TYPE,IMAGES,CONDITION,COLOR,DIMENSIONS,TAGS,...,Ownership,Condition,SKU,DONATION FY26 (Y/N),Notes,Availability,Retail($),Cost($),Dest (Y/N),RETAIL YEAR
2,7003417,Available,BARRETT KNURLED BOOM-ARM DESK LIGHT,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MULTIPLE SCRATCHES AND MULTIPLE PRINT MARKS TO...,NATURAL BRASS,36 x 9 x 20 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,7003443,Available,BOXED CARTHAGE TL,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS,NATURAL BRASS,28 x 16 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7003445,Available,BOXED FLOOR LAMP,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES ON LAMP PIECES SEPARATED IN BOX.,POLISHED NICKEL,43 x 13 x 7 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7003442,Available,BOXED CARTHAGE TABLE LAMP,Home 888 Madison,LIGHTING,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR SCRATCHES COMES WITH HARDWARE AND INSTRU...,NATURAL BRASS,27 x 15.5 x 14 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,7003550,Available,ANTIQUE ROUND TABLE TOP,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,TOP SURFACE AND TOP EDGES HAVE MULTIPLE SCRATC...,NaN,72 x 72 x 30.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,7003400,Available,2 LEAVES FOR HUDSON ST DINING TABLE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH HUDSON ST DINING TABLE 007002939. MI...,NaN,51 x 24 x 5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,7003433,Available,CLIVEDON SERVER MARBLE TOP,Home 888 Madison,CONSOLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,OLD BARCODES 07002891\n007002890 / CLIVEDON SE...,BLACK,73 x 23 x 1 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420,7003315,Available,EDWARDIAN BOOKCASE CROWN + BASE,Home 888 Madison,BOOKCASE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,"COMES WITH SHLVES, HARDWARE. MINOR MARKS ON ED...",NaN,82.5 x 16 x 7 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,7003316,Available,EDWARDIAN BOOKCASE CROWN + BASE,Home 888 Madison,BOOKCASE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,MINOR MARKS AND SCRATCHES ALONG EDGES AND CORN...,NaN,82.5 x 16 x 7 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,7002739,Available,EMPIRE PEDESTAL TABLE BASE,Home 888 Madison,TABLE,https://flo-rlassets.s3.eu-west-1.amazonaws.co...,GOES WITH EMPIRE PEDESTAL DINING TABLE TOP: 00...,NaN,40.5 x 40.5 x 26.5 Inches,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
concat_df.to_csv('Output/difference.csv',index=False)